version: "3.9"

networks:
  idm_network:

services:
  postgres:
    container_name: postgres_container
    image: postgres:17.5-alpine3.21
    hostname: idm-db
    environment:
      POSTGRES_DB: 'idm_db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'user'
    volumes:
      - .data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - idm_network